# Generated by Django 4.2 on 2023-12-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UserProfileId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Picture', models.FileField(blank=True, max_length=300, null=True, upload_to='uploads/user_profiles', verbose_name='Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
