"""
Django settings for my_s3 project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2%iu9q_n#5#7owz072#qwp(51-o9fc7j2$-sjm7w=p_bb_9#oi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'profiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Handling File Storage
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_ACCESS_KEY_ID = 'AKIAQ5LI4O4FJVE4RE4R'
AWS_S3_SECRET_ACCESS_KEY = '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'
AWS_S3_REGION_NAME = 'ap-south-1'
AWS_STORAGE_BUCKET_NAME = 'localhost-project'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_NAME = 's3v4'
AWS_S3_VERIFY = True
AWS_DEFAULT_ACL = None

# AWS_SESSION_TOKEN = None
# AWS_S3_SESSION_PROFILE = None
# AWS_S3_OBJECT_PARAMETERS = None
# AWS_QUERYSTRING_AUTH = None
# AWS_QUERYSTRING_EXPIRE = None
# AWS_S3_SIGNATURE_VERSION = None
# AWS_LOCATION = None
# AWS_S3_CUSTOM_DOMAIN = None
# AWS_CLOUDFRONT_KEY_ID = None
# AWS_CLOUDFRONT_KEY = None
# AWS_S3_ADDRESSING_STYLE = None
# AWS_S3_FILE_NAME_CHARSET = None
# AWS_IS_GZIPPED = None
# GZIP_CONTENT_TYPES = None
# AWS_S3_URL_PROTOCOL = None
# AWS_S3_ENDPOINT_URL = None
# AWS_S3_PROXIES = None
# AWS_S3_USE_SSL = None
# AWS_S3_MAX_MEMORY_SIZE = None
# AWS_S3_USE_THREADS = None
# AWS_S3_TRANSFER_CONFIG = None

